"""Generate the i2RT gripper model + config for the yubi_4310 gripper.

Run after cad/build.py and sim/finger_sweep.py:

    python3 sim/build_model.py

Writes into sdk/overlay/ (the files that get copied into an i2RT checkout):
  i2rt/robot_models/gripper/yubi_4310/yubi_4310.xml   MuJoCo model, i2RT layout
  i2rt/robot_models/gripper/yubi_4310/assets/*.stl     meshes in the gripper frame
  i2rt/robots/config/yubi_4310.yml                     motor, limits, force limiter

The model follows i2RT's linear_4310.xml: a body named "gripper" (merged into the
arm's last link by combine_arm_and_gripper_xml), finger joint "joint7" right after
the six arm joints with its range ordered [closed, open], and the second finger
"joint8" coupled to it by an equality constraint (here: the gears make it -joint7).
"""
import json
import math
import os
import shutil

import numpy as np
import trimesh

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(HERE, "assets")
OVERLAY = os.path.join(ROOT, "sdk/overlay/i2rt")
GRIP_DIR = os.path.join(OVERLAY, "robot_models/gripper/yubi_4310")
CFG_DIR = os.path.join(OVERLAY, "robots/config")

build = json.load(open(os.path.join(ROOT, "cad/out/build_summary.json")))
travel = json.load(open(os.path.join(HERE, "finger_travel.json")))
sim = build["sim"]

q_closed = math.radians(travel["closed_deg"])
q_open = math.radians(travel["open_deg"])
gap_open_m = travel["pad_gap_at_open_mm"] / 1000.0


def f(v):
    return " ".join(f"{x:.6g}" for x in v)


def load(name):
    return trimesh.load(os.path.join(ASSETS, f"{name}.stl"), force="mesh")


# ---- mass properties: estimates from CAD volumes and materials (cad/build.py) --------
base = load("base")
mass_base = build["mass_kg"]["base"]
mass_r, mass_l = build["mass_kg"]["finger_r"], build["mass_kg"]["finger_l"]


def inertial(mesh, mass):
    hull = mesh.convex_hull
    com = hull.center_mass
    I = hull.moment_inertia / hull.mass * mass if hull.mass > 0 else np.eye(3) * 1e-6
    w, _ = np.linalg.eigh(I)
    return com, np.clip(w, 1e-7, None)


com_b, I_b = inertial(base, mass_base)
fr, fl = load("finger_r"), load("finger_l")
ar, al = np.array(sim["axis_r"]), np.array(sim["axis_l"])
com_r, I_r = inertial(fr, mass_r)
com_l, I_l = inertial(fl, mass_l)

# grasp site: between the pad tips, on the gripper axis plane of the pads
pr, pl = load("pad_r"), load("pad_l")
tip_z = max(pr.bounds[0][2], pl.bounds[0][2]) + 0.008        # 8 mm up from the pad ends
pad_mid_y = 0.5 * (pr.centroid[1] + pl.centroid[1])
grasp = np.array([0.5 * (ar[0] + al[0]), pad_mid_y, tip_z])

xml = f"""<mujoco model="yubi_4310">
  <!-- Generated by yubi-yam/sim/build_model.py. YUBI gripper (Toyota/AIRoA, CERN-OHL-W-2.0)
       re-motored with a DM4310 for the I2RT YAM. Units: metres, radians. -->
  <compiler angle="radian" meshdir="assets"/>

  <asset>
    <mesh name="yubi_base" file="base.stl"/>
    <mesh name="yubi_finger_r" file="finger_r.stl"/>
    <mesh name="yubi_finger_l" file="finger_l.stl"/>
    <mesh name="yubi_pad_r" file="pad_r.stl"/>
    <mesh name="yubi_pad_l" file="pad_l.stl"/>
  </asset>

  <worldbody>
    <body name="gripper" pos="0 0 0" quat="0 0.70711 0.70711 0">
      <inertial pos="{f(com_b)}" mass="{mass_base:.4f}" diaginertia="{f(I_b)}"/>
      <geom type="mesh" mesh="yubi_base" rgba="0.23 0.25 0.27 1" contype="0" conaffinity="0"/>
      <site name="tcp_site" pos="0 0 0" quat="0 1 0 0" size="0.005" rgba="1 0 0 1"/>
      <!-- grasp_site: between the pads, 8 mm up from their tips; fixed for all openings
           to within a few mm (the fingers pivot, so the pinch point moves slightly). -->
      <site name="grasp_site" pos="{f(grasp)}" quat="0 1 0 0" size="0.005" rgba="0 1 0 1"/>
      <body name="finger_r" pos="{f(ar)}">
        <inertial pos="{f(com_r - ar)}" mass="{mass_r:.4f}" diaginertia="{f(I_r)}"/>
        <joint name="joint7" type="hinge" axis="0 1 0" range="{q_closed:.5f} {q_open:.5f}" damping="0.02"/>
        <geom type="mesh" mesh="yubi_finger_r" pos="{f(-ar)}" rgba="0.78 0.20 0.17 1" contype="0" conaffinity="0"/>
        <geom name="pad_r" type="mesh" mesh="yubi_pad_r" pos="{f(-ar)}" rgba="0.08 0.08 0.08 1" friction="1.2 0.02 0.002"/>
      </body>
      <body name="finger_l" pos="{f(al)}">
        <inertial pos="{f(com_l - al)}" mass="{mass_l:.4f}" diaginertia="{f(I_l)}"/>
        <joint name="joint8" type="hinge" axis="0 1 0" range="{-q_open:.5f} {-q_closed:.5f}" damping="0.02"/>
        <geom type="mesh" mesh="yubi_finger_l" pos="{f(-al)}" rgba="0.78 0.20 0.17 1" contype="0" conaffinity="0"/>
        <geom name="pad_l" type="mesh" mesh="yubi_pad_l" pos="{f(-al)}" rgba="0.08 0.08 0.08 1" friction="1.2 0.02 0.002"/>
      </body>
    </body>
  </worldbody>

  <equality>
    <!-- 1:1 spur gears: the left finger turns opposite to the right one -->
    <joint joint1="joint8" joint2="joint7" polycoef="0 -1 0 0 0"/>
  </equality>

  <contact>
    <exclude body1="gripper" body2="finger_r"/>
    <exclude body1="gripper" body2="finger_l"/>
    <exclude body1="finger_r" body2="finger_l"/>
  </contact>
</mujoco>
"""

yml = f"""# yubi_4310: YUBI bidigital gripper (Toyota / AIRoA, CERN-OHL-W-2.0) re-motored with
# the DM4310 from the stock YAM gripper. Generated by yubi-yam/sim/build_model.py.
#
# The 4310 drives one finger's gear shaft directly (1:1), the gears turn the other
# finger. Finger travel from CAD: closed (pads touching) {travel['closed_deg']} deg,
# open {travel['open_deg']} deg = {math.degrees(q_open - q_closed):.1f} deg of motor travel,
# {travel['pad_gap_at_open_mm']:.1f} mm between the pads. Less than one motor turn, so
# once measured the limits can be written below and calibration turned off.

# The yubi-yam wrist flange puts the gripper's mounting face where the stock grippers'
# is, so the mount transform is the stock one.
last_joint_mount:
  yam:
    v1:
      pos: "0.0404996 0 -0.0356"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  yam_pro:
    v1:
      pos: "0.0404996 0 -0.0356"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  yam_ultra:
    v1:
      pos: "0.0404996 0 -0.0419481"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
    v2:
      pos: "0.0404996 0 -0.0419481"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  big_yam:
    v1:
      pos: "0.0356 0 -0.0404996"
      quat: "0.5 -0.5 0.5 -0.5"
      axis: "0 0 1"

motor_type: "DM4310"
# No lead screw or rack between motor and fingers, so position gain is lower than
# linear_4310's 20.0: 1 N*m at the motor is ~{1 / (gap_open_m / (q_open - q_closed)):.0f} N at the pads.
motor_kp: 10.0
motor_kd: 0.3
# Closing should increase the motor reading (as on the stock gripper). If the
# fingers open when commanded closed, set this to -1.
motor_direction: 1

# [closed, open] in motor rad. null = auto-detect on start-up (drives gently to the
# closed stop, pads touching, and the open stop, fingers against the case).
gripper_limits: null
needs_calibration: true

limiter:
  clog_force_threshold: 0.5
  clog_speed_threshold: 0.3
  sign: 1.0
  force_torque_map: "linear"
  # average pad-gap change per motor radian over the travel
  motor_stroke: {q_open - q_closed:.4f}
  gripper_stroke: {gap_open_m:.4f}
"""

os.makedirs(os.path.join(GRIP_DIR, "assets"), exist_ok=True)
os.makedirs(CFG_DIR, exist_ok=True)
for n in ("base", "finger_r", "finger_l", "pad_r", "pad_l"):
    shutil.copy(os.path.join(ASSETS, f"{n}.stl"), os.path.join(GRIP_DIR, "assets", f"{n}.stl"))
open(os.path.join(GRIP_DIR, "yubi_4310.xml"), "w").write(xml)
open(os.path.join(CFG_DIR, "yubi_4310.yml"), "w").write(yml)
print(f"model: joint7 [{q_closed:.4f}, {q_open:.4f}] rad, base {mass_base:.3f} kg, "
      f"grasp_site {np.round(grasp, 4).tolist()}")
